name = "2014 FIFA World Cup"
seed = 12345678

root = "rank"

[[team]]
id = "bra"
name = "Brazil"
elo = 2238

[[team]]
id = "cro"
name = "Croatia"
elo = 1819

[[team]]
id = "mex"
name = "Mexico"
elo = 1814

[[team]]
id = "cmr"
name = "Cameroon"
elo = 1617

[[team]]
id = "esp"
name = "Spain"
elo = 2109

[[team]]
id = "ned"
name = "Netherlands"
elo = 1986

[[team]]
id = "chi"
name = "Chile"
elo = 1920

[[team]]
id = "aus"
name = "Australia"
elo = 1709

[[team]]
id = "col"
name = "Colombia"
elo = 1922

[[team]]
id = "gre"
name = "Greece"
elo = 1824

[[team]]
id = "civ"
name = "Ivory Coast"
elo = 1776

[[team]]
id = "jpn"
name = "Japan"
elo = 1786

[[team]]
id = "eng"
name = "England"
elo = 1932

[[team]]
id = "ita"
name = "Italy"
elo = 1888

[[team]]
id = "uru"
name = "Uruguay"
elo = 1919

[[team]]
id = "crc"
name = "Costa Rica"
elo = 1712

[[team]]
id = "fra"
name = "France"
elo = 1897

[[team]]
id = "hon"
name = "Honduras"
elo = 1670

[[team]]
id = "sui"
name = "Switzerland"
elo = 1856

[[team]]
id = "ecu"
name = "Ecuador"
elo = 1837

[[team]]
id = "arg"
name = "Argentina"
elo = 2019

[[team]]
id = "bih"
name = "Bosnia and Herzegovina"
elo = 1787

[[team]]
id = "iri"
name = "Iran"
elo = 1714

[[team]]
id = "nga"
name = "Nigeria"
elo = 1724

[[team]]
id = "ger"
name = "Germany"
elo = 2073

[[team]]
id = "por"
name = "Portugal"
elo = 1943

[[team]]
id = "gha"
name = "Ghana"
elo = 1710

[[team]]
id = "usa"
name = "United States"
elo = 1858

[[team]]
id = "bel"
name = "Belgium"
elo = 1853

[[team]]
id = "alg"
name = "Algeria"
elo = 1628

[[team]]
id = "rus"
name = "Russia"
elo = 1849

[[team]]
id = "kor"
name = "South Korea"
elo = 1668

[[format]]
id = "f_group"
mode = "roundrobin"
order = [[1,2], [3,4],
         [1,3], [4,2],
         [4,1], [2,3]]
neutral = true
rank_by = ["points", "goaldiff", "goals", "vspoints", "vsgoaldiff", "vsgoals"]

[[format]]
id = "f_playoff"
mode = "playoff"
random = false
neutral = true
rank_by = ["extra", "penalties"]

[[format]]
id = "f_ranking"
mode = "ranking"
rank_by = []

[[round]]
id = "group-a"
name = "Group A"
format = "f_group"
[[round.entrant]]
    id = "bra"
[[round.entrant]]
    id = "cro"
[[round.entrant]]
    id = "mex"
[[round.entrant]]
    id = "cmr"

[[round]]
id = "group-b"
name = "Group B"
format = "f_group"
[[round.entrant]]
    id = "esp"
[[round.entrant]]
    id = "ned"
[[round.entrant]]
    id = "chi"
[[round.entrant]]
    id = "aus"

[[round]]
id = "group-c"
name = "Group C"
format = "f_group"
[[round.entrant]]
    id = "col"
[[round.entrant]]
    id = "gre"
[[round.entrant]]
    id = "civ"
[[round.entrant]]
    id = "jpn"

[[round]]
id = "group-d"
name = "Group D"
format = "f_group"
[[round.entrant]]
    id = "eng"
[[round.entrant]]
    id = "ita"
[[round.entrant]]
    id = "uru"
[[round.entrant]]
    id = "crc"

[[round]]
id = "group-e"
name = "Group E"
format = "f_group"
[[round.entrant]]
    id = "fra"
[[round.entrant]]
    id = "hon"
[[round.entrant]]
    id = "sui"
[[round.entrant]]
    id = "ecu"

[[round]]
id = "group-f"
name = "Group F"
format = "f_group"
[[round.entrant]]
    id = "arg"
[[round.entrant]]
    id = "bih"
[[round.entrant]]
    id = "iri"
[[round.entrant]]
    id = "nga"

[[round]]
id = "group-g"
name = "Group G"
format = "f_group"
[[round.entrant]]
    id = "ger"
[[round.entrant]]
    id = "por"
[[round.entrant]]
    id = "gha"
[[round.entrant]]
    id = "usa"

[[round]]
id = "group-h"
name = "Group H"
format = "f_group"
[[round.entrant]]
    id = "bel"
[[round.entrant]]
    id = "alg"
[[round.entrant]]
    id = "rus"
[[round.entrant]]
    id = "kor"

[[round]]
id = "r16"
name = "Round of 16"
format = "f_playoff"
[[round.entrant]]
    prev = "group-a"
    pos = 1
[[round.entrant]]
    prev = "group-b"
    pos = 2
[[round.entrant]]
    prev = "group-c"
    pos = 1
[[round.entrant]]
    prev = "group-d"
    pos = 2
[[round.entrant]]
    prev = "group-b"
    pos = 1
[[round.entrant]]
    prev = "group-a"
    pos = 2
[[round.entrant]]
    prev = "group-d"
    pos = 1
[[round.entrant]]
    prev = "group-c"
    pos = 2
[[round.entrant]]
    prev = "group-e"
    pos = 1
[[round.entrant]]
    prev = "group-f"
    pos = 2
[[round.entrant]]
    prev = "group-g"
    pos = 1
[[round.entrant]]
    prev = "group-h"
    pos = 2
[[round.entrant]]
    prev = "group-f"
    pos = 1
[[round.entrant]]
    prev = "group-e"
    pos = 2
[[round.entrant]]
    prev = "group-h"
    pos = 1
[[round.entrant]]
    prev = "group-g"
    pos = 2

[[round]]
id = "qf"
name = "Quarterfinals"
format = "f_playoff"
[[round.entrant]]
    prev = "r16"
    pos = 5
[[round.entrant]]
    prev = "r16"
    pos = 6
[[round.entrant]]
    prev = "r16"
    pos = 1
[[round.entrant]]
    prev = "r16"
    pos = 2
[[round.entrant]]
    prev = "r16"
    pos = 7
[[round.entrant]]
    prev = "r16"
    pos = 8
[[round.entrant]]
    prev = "r16"
    pos = 3
[[round.entrant]]
    prev = "r16"
    pos = 4

[[round]]
id = "sf"
name = "Semifinals"
format = "f_playoff"
[[round.entrant]]
    prev = "qf"
    pos = 2
[[round.entrant]]
    prev = "qf"
    pos = 1
[[round.entrant]]
    prev = "qf"
    pos = 4
[[round.entrant]]
    prev = "qf"
    pos = 3

[[round]]
id = "3p"
name = "Third place play-off"
format = "f_playoff"
[[round.entrant]]
    prev = "sf"
    pos = 3
[[round.entrant]]
    prev = "sf"
    pos = 4

[[round]]
id = "fi"
name = "Final"
format = "f_playoff"
[[round.entrant]]
    prev = "sf"
    pos = 1
[[round.entrant]]
    prev = "sf"
    pos = 2

[[round]]
id = "rank"
name = "Final ranking"
format = "f_ranking"
[[round.entrant]]
    prev = "fi"
    pos = 1
[[round.entrant]]
    prev = "fi"
    pos = 2
[[round.entrant]]
    prev = "3p"
    pos = 1
[[round.entrant]]
    prev = "3p"
    pos = 2